### PR TITLE
Seesawify & add a re-awb resetter

### PR DESCRIPTION
**Pull request by ladyada**
req digitalio instead of pins for resetting - this is a breaking change but i dont think anyone's using this code
make reset match datasheet/appnote
the awb reset list is brute force but seems to work

### CODE REVIEW

**Review by jepler — COMMENTED** [review]
I'd approve it but apparently pre-commit does not. :-(

**Comment by ladyada** [comment]
iz ok - ill fix it up in a bit!

**Comment by FoamyGuy** [comment]
I pushed a new commit with precommit changes.

**Review by jepler — APPROVED** [review]
Thank you!

**Pull request merged**
